In [95]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [96]:
data = pd.read_csv('kc_house_data.csv')
data.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [97]:
dataTrain = pd.read_csv('kc_house_train_data.csv')
dataTest = pd.read_csv('kc_house_test_data.csv')

In [89]:
dataTrain.columns


Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [90]:
dataTrain = dataTrain[['sqft_living', 'bedrooms', 'bathrooms', 'lat', 'long', 'price']]
dataTest = dataTest[['sqft_living', 'bedrooms', 'bathrooms', 'lat', 'long', 'price']]

dataTrain.head()

sqft_living  bedrooms  bathrooms      lat     long     price
0         1180         3       1.00  47.5112 -122.257  221900.0
1         2570         3       2.25  47.7210 -122.319  538000.0
2          770         2       1.00  47.7379 -122.233  180000.0
3         1960         4       3.00  47.5208 -122.393  604000.0
4         1680         3       2.00  47.6168 -122.045  510000.0

In [57]:
dataTest.head()

sqft_living  bedrooms  bathrooms      lat     long     price
0         1430         3        1.0  47.7558 -122.229  310000.0
1         2950         4        3.0  47.5714 -122.375  650000.0
2         1710         3        2.0  47.3048 -122.218  233000.0
3         2320         3        2.5  47.5391 -122.070  580500.0
4         1090         3        1.0  47.6889 -122.375  535000.0

In [14]:
#X = np.array(dataTrain[['sqft_living', 'bedrooms', 'bathrooms']])
#y = np.array(dataTrain[['price']])

In [34]:
#xTest = np.array(dataTest[['sqft_living', 'bedrooms', 'bathrooms']])
#yTest = np.array(dataTest[['price']])

In [17]:
#from sklearn.linear_model import LinearRegression
#model = LinearRegression( fit_intercept=True, normalize=False).fit(X,y)

In [19]:
#model.coef_

array([[   315.40669062, -65081.88711588,   6942.16598637]])

In [21]:
#model.intercept_

array([87912.86581496])

In [26]:
#result = model.predict(X)

In [27]:
#result[0]

array([271789.26537997])

In [110]:
# Compute RSS
def get_residual_sum_of_squares(model, data, outcome):
    # First get the predictions
    predictedValues = model.predict(data)
    # Then compute the residuals/errors
    rss = sum((predictedValues-outcome)**2)
    # Then square and add them up
    return rss    

In [36]:
#rss = get_residual_sum_of_squares(model,Xtest, yTest)

In [37]:
#rss

array([2.73761941e+14])

In [98]:
# create some new featres as advised
dataTrain[['bedrooms_squared']] = dataTrain[['bedrooms']].apply(lambda x: x**2)
dataTrain['bed_bath_rooms'] = dataTrain['bedrooms']*dataTrain['bathrooms']
dataTrain[['log_sqft_living']] = dataTrain[['sqft_living']].apply(lambda x: np.log(x))
dataTrain['lat_long_plus'] = dataTrain['lat']+dataTrain['long']

dataTest[['bedrooms_squared', 'bathrooms_squared']] = dataTest[['bedrooms','bathrooms']].apply(lambda x: x**2)
dataTest['bed_bath_rooms'] = dataTest['bedrooms']*dataTest['bathrooms']
dataTest[['log_sqft_living']] = dataTest[['sqft_living']].apply(lambda x: np.log(x))
dataTest['lat_long_plus'] = dataTest['lat']+dataTest['long']

In [99]:
dataTest['bedrooms_squared'].mean()

12.4466777015843

In [100]:
dataTest['bed_bath_rooms'].mean()

7.5039016315913925

In [101]:
dataTest['log_sqft_living'].mean()

7.550274679645921

In [102]:
dataTest['lat_long_plus'].mean()

-74.65333355403185

## Learning Multiple Models

In [105]:
yTrain = np.array(dataTrain[['price']])
yTest = np.array(dataTest[['price']])

In [103]:
Xtrain1 = dataTrain[['sqft_living', 'bedrooms', 'bathrooms', 'lat', 'long']]
Xtest1 = dataTest[['sqft_living', 'bedrooms', 'bathrooms', 'lat', 'long']]

Xtrain2 = dataTrain[['sqft_living', 'bedrooms', 'bathrooms', 'lat', 'long', 'bed_bath_rooms']]
Xtest2 = dataTest[['sqft_living', 'bedrooms', 'bathrooms', 'lat', 'long', 'bed_bath_rooms']]

Xtrain3 = dataTrain[['sqft_living', 'bedrooms', 'bathrooms', 'lat', 'long', 'bed_bath_rooms', 'bedrooms_squared', 'log_sqft_living', 'lat_long_plus']]
Xtest3 = dataTest[['sqft_living', 'bedrooms', 'bathrooms', 'lat', 'long', 'bed_bath_rooms', 'bedrooms_squared', 'log_sqft_living', 'lat_long_plus']]

In [107]:
from sklearn.linear_model import LinearRegression
model1 = LinearRegression( fit_intercept=True, normalize=False).fit(np.array(Xtrain1),yTrain)
model1.coef_

array([[ 3.12258646e+02, -5.95865332e+04,  1.57067421e+04,
         6.58619264e+05, -3.09374351e+05]])

In [108]:
model2 = LinearRegression( fit_intercept=True, normalize=False).fit(np.array(Xtrain2),yTrain)
model2.coef_

array([[ 3.06610053e+02, -1.13446368e+05, -7.14613083e+04,
         6.54844630e+05, -2.94298969e+05,  2.55796520e+04]])

In [109]:
model3 = LinearRegression( fit_intercept=True, normalize=False).fit(np.array(Xtrain3),yTrain)
model3.coef_

array([[ 5.29422820e+02,  3.45142296e+04,  6.70607813e+04,
         5.34085611e+05, -4.06750711e+05, -8.57050439e+03,
        -6.78858667e+03, -5.61831484e+05,  1.27334900e+05]])

In [112]:
get_residual_sum_of_squares(model1, Xtest1, yTest)

array([2.2550047e+14])

In [113]:
get_residual_sum_of_squares(model2, Xtest2, yTest)

array([2.23377463e+14])

In [114]:
get_residual_sum_of_squares(model3, Xtest3, yTest)

array([2.59236319e+14])

In [115]:
get_residual_sum_of_squares(model1, Xtrain1, yTrain)

array([9.67879963e+14])

In [116]:
get_residual_sum_of_squares(model2, Xtrain2, yTrain)

array([9.58419635e+14])

In [117]:
get_residual_sum_of_squares(model3, Xtrain3, yTrain)

array([9.03436455e+14])